CREATE DATABASE TCC4μ
USE TCC4μ

CREATE TABLE CONTATO_EMPRESA (
	CONT_EMPRESA_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_CONTATO_ID PRIMARY KEY,
	CONT_EMPRESA_STR_EMAIL VARCHAR(50) NOT NULL,
	CONT_EMPRESA_STR_NOME VARCHAR(30) NOT NULL,
	CONT_EMPRESA_STR_MSG VARCHAR(500) NOT NULL,
	CONT_EMPRESA_DATETIME_EMISSAO DATETIME NOT NULL
)

CREATE TABLE LOGIN (
	LGN_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_LOGIN_ID PRIMARY KEY,
	LGN_STR_EMAIL VARCHAR(50) NOT NULL,
	LGN_STR_SENHA VARCHAR(50) NOT NULL,
	LGN_STR_TIME VARCHAR(50) NOT NULL
)