CREATE DATABASE TCC4μ
USE TCC4μ

CREATE TABLE CONTATO
(
	CONT_INT_ID INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_CONTATO_ID PRIMARY KEY,
	CONT_STR_EMAIL VARCHAR(50) NOT NULL,
	CONT_STR_NOME VARCHAR(30) NOT NULL,
	CONT_STR_MSG VARCHAR(500) NOT NULL,
	CONT_DATETIME_EMISSAO DATETIME NOT NULL
)

SELECT * FROM CONTATO

DROP TABLE CONTATO